object Versions {
    const val core = "1.8.0"
    const val compose = "1.3.0-alpha01"
    const val composeCompiler = "1.3.0"
    const val coilCompose = "2.2.1"
    const val viewModelCompose = "2.5.1"
    const val activityCompose = "1.5.0"
    const val hiltNavCompose = "1.0.0"
    const val lifecycle = "2.5.0"
    const val hilt = "2.42"
    const val media = "1.6.0"
    const val coroutines = "1.6.4"
    const val exoplayer = "2.18.1"

    const val junit = "4.13.2"
    const val testExtJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val truth = "1.1.3"
    const val robolectric = "4.8.1"
}